import 'package:tunefun_front/models/article_model.dart';

class DummyData {
  static List<ArticleModel> articles = [
    ArticleModel(
      id: 0,
      title: '백예린',
      uuid: '',
      content: '추운 겨울, 따뜻한 코코아 한 잔 같은 커버',
      votes: 339,
      likes: 506,
      articleType: '',
      username: '배예린',
      createdAt: DateTime(2024, 1, 14),
      updatedAt: DateTime(2024, 1, 14),
      deletedAt: DateTime.now(),
    ),
    ArticleModel(
      id: 0,
      title: '로이킴',
      uuid: '',
      content: '불멍 분위기의 노래 부를까요?',
      votes: 820,
      likes: 1234,
      articleType: '',
      username: '로이킴',
      createdAt: DateTime(2024, 1, 4),
      updatedAt: DateTime(2024, 1, 4),
      deletedAt: DateTime.now(),
    ),
    ArticleModel(
      id: 0,
      title: '에스파',
      uuid: '',
      content: '눈이 내리는 순간의 노래',
      votes: 9341,
      likes: 34642,
      articleType: '',
      username: '에스파',
      createdAt: DateTime(2023, 12, 24),
      updatedAt: DateTime(2023, 12, 24),
      deletedAt: DateTime.now(),
    ),
    ArticleModel(
      id: 0,
      title: '박효신',
      uuid: '',
      content: '오늘의 기분은 어떤가요?',
      votes: 254353,
      likes: 34626,
      articleType: '',
      username: '박효신',
      createdAt: DateTime(2023, 10, 12),
      updatedAt: DateTime(2023, 10, 12),
      deletedAt: DateTime.now(),
    ),
    ArticleModel(
      id: 0,
      title: '수퍼비',
      uuid: '',
      content: '바운스 바운스',
      votes: 9543,
      likes: 43566,
      articleType: '',
      username: '수퍼비',
      createdAt: DateTime(2023, 8, 5),
      updatedAt: DateTime(2023, 8, 5),
      deletedAt: DateTime.now(),
    ),
    ArticleModel(
      id: 0,
      title: '크러쉬',
      uuid: '',
      content: '감성 한스푼',
      votes: 45342,
      likes: 346695,
      articleType: '',
      username: '크러쉬',
      createdAt: DateTime(2023, 12, 31),
      updatedAt: DateTime(2023, 12, 31),
      deletedAt: DateTime.now(),
    ),
    ArticleModel(
      id: 0,
      title: 'Coldplay',
      uuid: '',
      content: '따뜻한 봄 같은 노래',
      votes: 2464436,
      likes: 4566324,
      articleType: '',
      username: 'Coldplay',
      createdAt: DateTime(2023, 12, 25),
      updatedAt: DateTime(2023, 12, 25),
      deletedAt: DateTime.now(),
    ),
  ];
}
